"""
PocketSmart AI - Unified Recommendation Service
Orchestrates recommendation generation for Home, Party, and Jewelry planners.
Normalizes data structures, integrates platform adapters and Gemini AI,
computes budget distributions, and persists results to the database.
"""

import os
import json
import logging
import urllib.parse
from typing import Dict, Any, List, Optional, Tuple
from database.database import get_db_connection
from models.planner import HomePlannerInput, PartyPlannerInput, JewelryPlannerInput
from models.recommendation import RecommendationItem, RecommendationSummary, BudgetAllocation
from services.budget_service import (
    calculate_home_budget_allocation,
    calculate_party_budget_allocation,
    calculate_jewelry_budget_allocation,
    evaluate_budget_status
)
from services.platforms.amazon import get_amazon_product_recommendations, get_amazon_search_url
from services.platforms.flipkart import get_flipkart_product_recommendations, get_flipkart_search_url
from services.platforms.ikea import get_ikea_product_recommendations, get_ikea_search_url
from services.platforms.swiggy import get_swiggy_search_url
from services.platforms.zomato import get_zomato_search_url
from services.platforms.oyo import get_oyo_search_url
from services.location_service import search_nearby_venues, get_google_maps_url
from services.platforms.jeweler_shops import (
    JEWELER_BRANDS,
    REAL_JEWELRY_CATALOG,
    get_jeweler_search_url,
    get_nearby_jeweler_shops
)
from services.gemini_service import (
    generate_ai_text_recommendations,
    analyze_outfit_image_for_jewelry,
    is_ai_available
)

logger = logging.getLogger(__name__)

def save_recommendation_history(
    user_id: int,
    planner_type: str,
    total_budget: float,
    input_data: Dict[str, Any],
    summary: RecommendationSummary
) -> int:
    """Save user planner request and resulting items into the database."""
    conn = get_db_connection()
    cursor = conn.cursor()

    # 1. Save planner request
    cursor.execute("""
        INSERT INTO planner_requests (user_id, planner_type, total_budget, input_data)
        VALUES (?, ?, ?, ?)
    """, (user_id, planner_type, total_budget, json.dumps(input_data)))
    request_id = cursor.lastrowid

    # 2. Save recommendation history
    cursor.execute("""
        INSERT INTO recommendation_histories (
            user_id, planner_request_id, planner_type, total_budget,
            allocated_spend, estimated_travel, remaining_budget, status, summary_text
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        user_id, request_id, planner_type, total_budget,
        summary.total_spend, summary.total_travel_estimate, summary.remaining_budget,
        summary.budget_status, summary.ai_summary or "Plan generated by PocketSmart AI"
    ))
    history_id = cursor.lastrowid

    # 3. Save recommendation items
    for item in summary.items:
        cursor.execute("""
            INSERT INTO recommendation_results (
                history_id, name, category, description, price, quantity,
                total_price, platform, url, reason, distance_km, travel_time_minutes,
                travel_cost_estimate, rating, review_count, location, is_mock
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            history_id, item.name, item.category, item.description,
            item.price, item.quantity, item.total_price, item.platform,
            item.url, item.reason, item.distance_km, item.travel_time_minutes,
            item.travel_cost_estimate, item.rating, item.review_count,
            item.location, 1 if item.is_mock else 0
        ))

    conn.commit()
    conn.close()
    return history_id

# =====================================================================
# 1. HOME INTERIOR PLANNER
# =====================================================================

async def generate_home_recommendations(
    planner_input: HomePlannerInput,
    user_id: Optional[int] = None
) -> Tuple[RecommendationSummary, Optional[int]]:
    """Generate budget-aware recommendations for home interior spaces."""
    budget = planner_input.total_budget
    allocations = calculate_home_budget_allocation(budget)
    items: List[RecommendationItem] = []
    is_live_ai = False
    ai_summary = ""

    # Platform adapters seed data based on requested quantities
    # Lighting
    if planner_input.num_lights > 0:
        light_budget = next(a.allocated_amount for a in allocations if a.category == "Lighting")
        amazon_lights = get_amazon_product_recommendations("lighting", light_budget)
        if amazon_lights:
            choice = amazon_lights[0]
            qty = min(planner_input.num_lights, 4)
            items.append(RecommendationItem(
                name=choice["name"],
                category="Lighting",
                description=f"Energy-efficient warm white lighting for {planner_input.room_type}.",
                price=choice["price"],
                quantity=qty,
                total_price=choice["price"] * qty,
                platform="Amazon",
                url=choice["url"],
                reason=choice["reason"],
                rating=choice["rating"],
                review_count=choice["review_count"]
            ))

    # Ceiling Fans
    if planner_input.num_fans > 0:
        fan_budget = next(a.allocated_amount for a in allocations if a.category == "Ceiling Fans")
        fan_picks = get_amazon_product_recommendations("ceiling fans", fan_budget)
        if fan_picks:
            choice = fan_picks[0]
            items.append(RecommendationItem(
                name=choice["name"],
                category="Ceiling Fans",
                description=f"Silent BLDC energy-saving cooling for {planner_input.room_type}.",
                price=choice["price"],
                quantity=planner_input.num_fans,
                total_price=choice["price"] * planner_input.num_fans,
                platform="Amazon",
                url=choice["url"],
                reason=choice["reason"],
                rating=choice["rating"],
                review_count=choice["review_count"]
            ))

    # Furniture
    if planner_input.num_furniture > 0:
        furn_budget = next(a.allocated_amount for a in allocations if a.category == "Furniture")
        ikea_furn = get_ikea_product_recommendations("furniture", furn_budget)
        flipkart_furn = get_flipkart_product_recommendations("furniture", furn_budget)
        
        if ikea_furn:
            choice = ikea_furn[0]
            items.append(RecommendationItem(
                name=choice["name"],
                category="Furniture",
                description=f"Scandinavian functional furniture suited for {planner_input.style_preference} styling.",
                price=choice["price"],
                quantity=1,
                total_price=choice["price"],
                platform="IKEA",
                url=choice["url"],
                reason=choice["reason"],
                rating=choice["rating"],
                review_count=choice["review_count"]
            ))
        if flipkart_furn and planner_input.num_furniture > 1:
            choice = flipkart_furn[0]
            items.append(RecommendationItem(
                name=choice["name"],
                category="Furniture",
                description=f"Engineered durable living unit for {planner_input.room_type}.",
                price=choice["price"],
                quantity=1,
                total_price=choice["price"],
                platform="Flipkart",
                url=choice["url"],
                reason=choice["reason"],
                rating=choice["rating"],
                review_count=choice["review_count"]
            ))

    # Decor
    if planner_input.num_decor > 0:
        decor_budget = next(a.allocated_amount for a in allocations if a.category == "Decor")
        decor_picks = get_ikea_product_recommendations("decor", decor_budget)
        if decor_picks:
            choice = decor_picks[0]
            items.append(RecommendationItem(
                name=choice["name"],
                category="Decor",
                description=f"Aesthetic accent piece complementing {planner_input.style_preference} interior.",
                price=choice["price"],
                quantity=planner_input.num_decor,
                total_price=choice["price"] * planner_input.num_decor,
                platform="IKEA",
                url=choice["url"],
                reason=choice["reason"],
                rating=choice["rating"],
                review_count=choice["review_count"]
            ))

    # Optional Gemini enhancement for rich personalized notes
    if is_ai_available():
        prompt = f"""
Plan interior decor for a {planner_input.room_type} with a budget of INR ₹{budget:,.2f}.
Style: {planner_input.style_preference}.
Provide a brief 2-sentence summary explaining how to maximize this budget without overspending.
"""
        ai_resp = await generate_ai_text_recommendations(prompt)
        if ai_resp and isinstance(ai_resp, dict):
            ai_summary = ai_resp.get("summary", "")
            is_live_ai = True

    if not ai_summary:
        ai_summary = (
            f"Tailored for {planner_input.room_type} with {planner_input.style_preference} aesthetic. "
            f"Balanced across lighting, furniture, cooling, and decor within your ₹{budget:,.2f} budget."
        )

    # Calculate actual spends per category
    total_spend = sum(item.total_price for item in items)
    for alloc in allocations:
        alloc.spent_amount = sum(i.total_price for i in items if i.category.lower() == alloc.category.lower())

    remaining = round(budget - total_spend, 2)
    status_str = evaluate_budget_status(budget, total_spend)

    summary = RecommendationSummary(
        planner_type="home",
        total_budget=budget,
        total_spend=round(total_spend, 2),
        total_travel_estimate=0.0,
        effective_total=round(total_spend, 2),
        remaining_budget=remaining,
        budget_status=status_str,
        allocations=allocations,
        items=items,
        ai_summary=ai_summary,
        is_demo=not is_live_ai
    )

    history_id = None
    if user_id:
        history_id = save_recommendation_history(
            user_id=user_id,
            planner_type="home",
            total_budget=budget,
            input_data=planner_input.model_dump(),
            summary=summary
        )

    return summary, history_id

# =====================================================================
# 2. PARTY BUDGET PLANNER
# =====================================================================

async def generate_party_recommendations(
    planner_input: PartyPlannerInput,
    user_id: Optional[int] = None
) -> Tuple[RecommendationSummary, Optional[int]]:
    """
    Generate event budget plan with location-aware nearby venues,
    60km rule evaluation, travel costs, and catering/entertainment.
    """
    budget = planner_input.total_budget
    allocations = calculate_party_budget_allocation(budget, planner_input.accommodation_needed)
    items: List[RecommendationItem] = []
    total_travel_cost = 0.0

    # 1. Nearby venues if location provided
    if planner_input.user_latitude is not None and planner_input.user_longitude is not None:
        venues = await search_nearby_venues(
            user_lat=planner_input.user_latitude,
            user_lon=planner_input.user_longitude,
            event_type=planner_input.event_type,
            guest_count=planner_input.guest_count,
            budget=budget,
            travel_mode=planner_input.travel_mode or "car"
        )
        for v in venues[:3]:  # Top 3 location alternatives
            total_travel_cost = max(total_travel_cost, v["travel_cost_estimate"])
            items.append(RecommendationItem(
                name=v["name"],
                category=v["category"],
                description=v["description"],
                price=v["price"],
                quantity=1,
                total_price=v["price"],
                platform=v["platform"],
                url=v["url"],
                reason=v["reason"],
                distance_km=v["distance_km"],
                travel_time_minutes=v["travel_time_minutes"],
                travel_cost_estimate=v["travel_cost_estimate"],
                effective_total_cost=v["effective_total_cost"],
                rating=v["rating"],
                review_count=v["review_count"],
                location=v["location"],
                google_maps_url=v["google_maps_url"],
                is_nearby=v["is_nearby"]
            ))
    else:
        # Default venue suggestion when location permission denied / not provided
        venue_budget = next(a.allocated_amount for a in allocations if a.category == "Venue")
        items.append(RecommendationItem(
            name=f"Premium {planner_input.venue_preference} & Banquet Space",
            category="Venue",
            description=f"Event hall suitable for {planner_input.guest_count} guests. Location permission required for nearby distance.",
            price=venue_budget * 0.9,
            quantity=1,
            total_price=venue_budget * 0.9,
            platform="Local Venue Partner",
            url=get_google_maps_url(f"{planner_input.venue_preference} banquet hall"),
            reason=f"Standard banquet capacity for {planner_input.guest_count} guests within {planner_input.event_type} budget.",
            rating=4.4,
            review_count=210,
            location="Local City Area"
        ))

    # 2. Catering
    catering_budget = next(a.allocated_amount for a in allocations if a.category == "Catering")
    per_plate = round(catering_budget / max(1, planner_input.guest_count), 2)
    swiggy_url = get_swiggy_search_url(f"party catering {planner_input.catering_preference}")
    zomato_url = get_zomato_search_url(f"catering {planner_input.catering_preference}")
    
    items.append(RecommendationItem(
        name=f"Deluxe {planner_input.catering_preference} Catering Package",
        category="Catering",
        description=f"Multi-course spread with welcome drinks, appetizers, main course buffet, and desserts.",
        price=per_plate,
        quantity=planner_input.guest_count,
        total_price=catering_budget * 0.95,
        platform="Swiggy / Local Caterer",
        url=swiggy_url,
        reason=f"Calculated at ₹{per_plate:,.0f} per plate for {planner_input.guest_count} guests.",
        rating=4.5,
        review_count=340
    ))

    # 3. Decoration
    if planner_input.decoration_needed:
        decor_budget = next(a.allocated_amount for a in allocations if a.category == "Decoration")
        items.append(RecommendationItem(
            name=f"Theme Balloon & Floral Arch Decor ({planner_input.event_type})",
            category="Decoration",
            description="Stage backdrop, entrance arch, customized photo-booth, and ambient lighting.",
            price=decor_budget * 0.9,
            quantity=1,
            total_price=decor_budget * 0.9,
            platform="Local Decor Specialist",
            url=get_amazon_search_url(f"party decoration kit {planner_input.event_type}"),
            reason=f"Specially styled backdrop and lighting for {planner_input.event_type} celebration.",
            rating=4.3,
            review_count=150
        ))

    # 4. Entertainment
    if planner_input.entertainment_needed:
        ent_budget = next(a.allocated_amount for a in allocations if a.category == "Entertainment")
        items.append(RecommendationItem(
            name="Professional Sound System, DJ & Emcee Hosting",
            category="Entertainment",
            description="High-output audio setup, wireless microphones, party lighting effects, and host.",
            price=ent_budget * 0.85,
            quantity=1,
            total_price=ent_budget * 0.85,
            platform="Local Service Provider",
            url=get_google_maps_url("party dj sound system rental"),
            reason="Keeps guests engaged with quality audio and coordinated event games.",
            rating=4.6,
            review_count=98
        ))

    # 5. Accommodation (if requested)
    if planner_input.accommodation_needed:
        accom_budget = next(a.allocated_amount for a in allocations if a.category == "Accommodation")
        items.append(RecommendationItem(
            name="OYO / Partner Hotel Guest Suites (Block of 5 Rooms)",
            category="Accommodation",
            description="Air-conditioned double rooms with complimentary breakfast for out-of-town guests.",
            price=accom_budget * 0.9,
            quantity=1,
            total_price=accom_budget * 0.9,
            platform="OYO",
            url=get_oyo_search_url("party guest rooms"),
            reason="Clean, comfortable overnight stays close to the celebration venue.",
            rating=4.2,
            review_count=450
        ))

    total_spend = sum(item.total_price for item in items)
    effective_total = total_spend + total_travel_cost
    remaining = round(budget - effective_total, 2)
    status_str = evaluate_budget_status(budget, effective_total)

    # Update spent_amounts in allocations
    for alloc in allocations:
        alloc.spent_amount = sum(i.total_price for i in items if i.category.lower() == alloc.category.lower())

    summary = RecommendationSummary(
        planner_type="party",
        total_budget=budget,
        total_spend=round(total_spend, 2),
        total_travel_estimate=round(total_travel_cost, 2),
        effective_total=round(effective_total, 2),
        remaining_budget=remaining,
        budget_status=status_str,
        allocations=allocations,
        items=items,
        ai_summary=(
            f"Curated {planner_input.event_type} package for {planner_input.guest_count} guests. "
            f"Combines venue, catering, and travel estimates within ₹{budget:,.2f} budget."
        ),
        is_demo=False
    )

    history_id = None
    if user_id:
        history_id = save_recommendation_history(
            user_id=user_id,
            planner_type="party",
            total_budget=budget,
            input_data=planner_input.model_dump(),
            summary=summary
        )

    return summary, history_id

# =====================================================================
# 3. JEWELRY BUDGET PLANNER (TEXT & MULTIMODAL IMAGE)
# =====================================================================

async def generate_jewelry_recommendations(
    planner_input: JewelryPlannerInput,
    outfit_image_bytes: Optional[bytes] = None,
    outfit_image_mime: Optional[str] = None,
    user_id: Optional[int] = None
) -> Tuple[RecommendationSummary, Optional[int]]:
    """
    Generate authentic precious jewelry recommendations strictly for:
    Gold, Silver, Platinum, or Diamond from certified jeweller houses
    (Tanishq, CaratLane, BlueStone, Malabar Gold & Diamonds, Kalyan Jewellers, GIVA).
    STRICTLY NO bangles, NO imitation/costume jewelry.
    """
    budget = planner_input.total_budget
    allocations = calculate_jewelry_budget_allocation(budget)
    items: List[RecommendationItem] = []
    is_live_ai = False
    ai_summary = ""

    metal = planner_input.precious_metal or "Gold"
    valid_metals = ["Gold", "Silver", "Platinum", "Diamond"]
    matched_metal = next((m for m in valid_metals if m.lower() in metal.lower()), "Gold")
    if "all" in metal.lower():
        if budget < 10000:
            matched_metal = "Silver"
        elif budget < 35000:
            matched_metal = "Diamond"
        elif budget < 75000:
            matched_metal = "Gold"
        else:
            matched_metal = "Platinum"

    # Multimodal image analysis with Gemini AI
    if outfit_image_bytes and is_ai_available():
        ai_data = await analyze_outfit_image_for_jewelry(
            image_bytes=outfit_image_bytes,
            mime_type=outfit_image_mime or "image/jpeg",
            budget=budget,
            occasion=planner_input.occasion,
            style_preference=planner_input.style_preference,
            precious_metal=matched_metal
        )
        if ai_data and "recommendations" in ai_data:
            is_live_ai = True
            analysis = ai_data.get("outfit_analysis", {})
            ai_summary = (
                f"Outfit Analysis: {analysis.get('styling_advice', '')} "
                f"Recommended metal: {analysis.get('recommended_metal', matched_metal)}."
            )
            for rec in ai_data["recommendations"]:
                brand = rec.get("brand", "Tanishq")
                query = rec.get("search_query", rec.get("name", "fine jewelry"))
                url = get_jeweler_search_url(brand, query)
                maps_url = f"https://www.google.com/maps/search/{urllib.parse.quote_plus(f'{brand} showroom near me')}"
                price = float(rec.get("price", 5000.0))
                purity = rec.get("purity_certification", f"Certified {matched_metal}")
                items.append(RecommendationItem(
                    name=rec.get("name", f"Certified {matched_metal} Piece"),
                    category=rec.get("category", "Necklace / Pendant"),
                    description=rec.get("description", f"100% authentic {matched_metal} from {brand}."),
                    price=price,
                    quantity=1,
                    total_price=price,
                    platform=brand,
                    url=url,
                    google_maps_url=maps_url,
                    purity_badge=purity,
                    reason=rec.get("reason", f"Certified authentic {matched_metal} matching {planner_input.occasion}"),
                    rating=4.8,
                    review_count=1800
                ))

    # Catalog-driven matching for authentic Gold, Silver, Platinum, Diamond
    if not items:
        catalog_metal = matched_metal if matched_metal in REAL_JEWELRY_CATALOG else "Gold"
        metal_catalog = REAL_JEWELRY_CATALOG[catalog_metal]

        # 1. Necklace / Pendant (50% allocation)
        necklace_budget = next(a.allocated_amount for a in allocations if "Necklace" in a.category)
        necklace_picks = metal_catalog.get("Necklace", [])
        if necklace_picks:
            pick = min(necklace_picks, key=lambda x: abs(x["price"] - necklace_budget))
            unit_price = min(round(necklace_budget * 0.95, 2), pick["price"])
            if budget < 5000 and catalog_metal != "Silver":
                unit_price = min(necklace_budget, 1999.0)
            items.append(RecommendationItem(
                name=pick["name"],
                category="Necklace / Pendant",
                description=f"Authentic {pick['material']} jewel with {pick['purity']} from {pick['brand']}.",
                price=unit_price,
                quantity=1,
                total_price=unit_price,
                platform=pick["brand"],
                url=get_jeweler_search_url(pick["brand"], pick["name"]),
                google_maps_url=f"https://www.google.com/maps/search/{urllib.parse.quote_plus(pick['brand'] + ' jewellery showroom near me')}",
                purity_badge=pick["purity"],
                reason=pick["reason"],
                rating=pick["rating"],
                review_count=pick["review_count"]
            ))

        # 2. Earrings / Studs (30% allocation)
        earring_budget = next(a.allocated_amount for a in allocations if "Earrings" in a.category)
        earring_picks = metal_catalog.get("Earrings", [])
        if earring_picks:
            pick = min(earring_picks, key=lambda x: abs(x["price"] - earring_budget))
            unit_price = min(round(earring_budget * 0.95, 2), pick["price"])
            if budget < 5000 and catalog_metal != "Silver":
                unit_price = min(earring_budget, 1499.0)
            items.append(RecommendationItem(
                name=pick["name"],
                category="Earrings / Studs",
                description=f"Authentic {pick['material']} earrings with {pick['purity']} from {pick['brand']}.",
                price=unit_price,
                quantity=1,
                total_price=unit_price,
                platform=pick["brand"],
                url=get_jeweler_search_url(pick["brand"], pick["name"]),
                google_maps_url=f"https://www.google.com/maps/search/{urllib.parse.quote_plus(pick['brand'] + ' jewellery showroom near me')}",
                purity_badge=pick["purity"],
                reason=pick["reason"],
                rating=pick["rating"],
                review_count=pick["review_count"]
            ))

        # 3. Ring / Solitaire Band (20% allocation - strictly NO bangles)
        ring_budget = next(a.allocated_amount for a in allocations if "Ring" in a.category)
        ring_picks = metal_catalog.get("Ring", [])
        if ring_picks:
            pick = min(ring_picks, key=lambda x: abs(x["price"] - ring_budget))
            unit_price = min(round(ring_budget * 0.95, 2), pick["price"])
            if budget < 5000 and catalog_metal != "Silver":
                unit_price = min(ring_budget, 999.0)
            items.append(RecommendationItem(
                name=pick["name"],
                category="Ring / Solitaire",
                description=f"Authentic {pick['material']} ring with {pick['purity']} from {pick['brand']}.",
                price=unit_price,
                quantity=1,
                total_price=unit_price,
                platform=pick["brand"],
                url=get_jeweler_search_url(pick["brand"], pick["name"]),
                google_maps_url=f"https://www.google.com/maps/search/{urllib.parse.quote_plus(pick['brand'] + ' jewellery showroom near me')}",
                purity_badge=pick["purity"],
                reason=pick["reason"],
                rating=pick["rating"],
                review_count=pick["review_count"]
            ))

        ai_summary = (
            f"100% Authentic {matched_metal} Ensemble curated for {planner_input.occasion}. "
            f"Featuring certified hallmarks (BIS 916 / Pt 950 / 925 Silver / IGI Diamond) from verified jewellers "
            f"(Tanishq, CaratLane, BlueStone, Malabar Gold, GIVA) within ₹{budget:,.2f}."
        )

    # Nearby certified jeweler showrooms
    nearby_shops = get_nearby_jeweler_shops(planner_input.location or "nearby")

    total_spend = sum(item.total_price for item in items)
    remaining = round(budget - total_spend, 2)
    status_str = evaluate_budget_status(budget, total_spend)

    # Update allocated spent amounts
    for alloc in allocations:
        alloc.spent_amount = sum(i.total_price for i in items if i.category.lower() == alloc.category.lower())

    summary = RecommendationSummary(
        planner_type="jewelry",
        total_budget=budget,
        total_spend=round(total_spend, 2),
        total_travel_estimate=0.0,
        effective_total=round(total_spend, 2),
        remaining_budget=remaining,
        budget_status=status_str,
        allocations=allocations,
        items=items,
        ai_summary=ai_summary,
        nearby_shops=nearby_shops,
        is_demo=not is_live_ai
    )

    history_id = None
    if user_id:
        history_id = save_recommendation_history(
            user_id=user_id,
            planner_type="jewelry",
            total_budget=budget,
            input_data=planner_input.model_dump(),
            summary=summary
        )

    return summary, history_id
